### PR TITLE
✨ Enforce gitmoji in PR title

### LINKED ISSUE #92: Add gitmoji in PR title enforcement
Let's start documenting our commits to main properly to make our changelog better as soon as possible.
Please add the github action to enforce the gitmoji in PR titles.

### PR DESCRIPTION
**Pull request by rahulpatidar0191**
Enforces use of emojis for PR titles 
Closes https://github.com/SatelCreative/spylib/issues/92

### CODE REVIEW

**Review by hillairet — CHANGES_REQUESTED** [review]
Does the label definition do anything?
If not let's remove it.
If it does something, let's remove it too ...  :sweat_smile: 

Maybe the failure message could be more explicit than "Failing CI test".

**Comment by rahulpatidar0191** [comment]
@hillairet Label just adds a label to the PR saying `Title need formatting` It doesn't look like I can remove the label defination
Since it uses default config from [thehanimo/pr-title-checker](https://github.com/thehanimo/pr-title-checker/blob/fb85c5793d630c4ec3bc446981e68c4f62214f01/dist/index.js#L758) 

And in the actions I see this error 
```Run thehanimo/pr-title-checker@v1.[3](https://github.com/SatelCreative/spylib/runs/5761804006?check_suite_focus=true#step:2:3).[4](https://github.com/SatelCreative/spylib/runs/5761804006?check_suite_focus=true#step:2:4)
  with:
    GITHUB_TOKEN: ***
    pass_on_octokit_error: false
    configuration_path: .github/pr-title-checker-config.json
TypeError: Cannot read property 'name' of undefined

**Comment by rahulpatidar0191** [comment]
Leaving the label definition empty but it still picks up from the default i think, so you can see the label being added still

**Review by hillairet — APPROVED** [review]
That's dumb to force the label. It goes away when the gitmoji is added?
If it has to be here, feel free to improve the formatting/text. Could be "Gitmoji missing" since that's the only thing our checker enforces.

**Comment by rahulpatidar0191** [comment]
Yeah it goes away if the emoji is added. Only gets added if the PR title is missing an emoji

Okay I'll edit the text

**Pull request merged**
