### PR TITLE
🔖 Release/0.6.0

### PR DESCRIPTION
**Pull request by lishanl**
- update spylib version to 0.6.0
- add change log

### CODE REVIEW

**Comment by lishanl** [comment]
the change log doesn't look like what's expected 🤔

**Comment by hillairet** [comment]
What's not correct in the changelog???
Looks OK to me.

**Comment by lishanl** [comment]
> What's not correct in the changelog??? Looks OK to me.

yea looks ok after the update. I didn't do it right at the beginning, I ran only `auto-changelog`

**Comment by lishanl** [comment]
good to go?

**Review by hillairet — APPROVED** [review]
Cool

**Pull request merged**
